# Generated by Django 3.0.3 on 2023-09-03 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 3, 6, 53, 39, 897122, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
